configure: Add --noauto flag for disabling feature auto-detection to more closely match the configure script from the sdl20 branch.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -91,6 +91,10 @@ _WEJTEST
 		res=0
 	fi
 	rm -f /tmp/test.o /tmp/test.wej.c /tmp/test.exe
+	if [ "${res}" -eq 0 ] && [ "${auto_detect}" -eq 0 ]; then
+		echo "ERROR: Dependencies failed. Aborting."
+		exit 2
+	fi
 	return $res
 }
 
@@ -320,6 +324,7 @@ help()
 	echo "  --enable <feature>"
 	echo "  --disable <feature>"
 	echo "  --release (enables release build flags)"
+	echo "  --noauto (disables feature auto-detection)"
 	echo "  --target-device <device name>"
 	echo "  --sdk-path </path/to/sdk/base/dir>"
 	echo "  --help"
@@ -356,6 +361,8 @@ sdk_path=
 includes=
 libs=
 release_build=0
+# Unless we are told otherwise (--noauto), we enable feature auto-detection:
+auto_detect=-2
 
 # Parse options
 while :
@@ -365,28 +372,32 @@ do
 			help
 			exit 0
 			;;
+		-n | --noauto)
+			auto_detect=0
+			shift
+			;;
 		-e | --enable | --with)
-			enable=$2
-			if [ "$enable" = "" ]; then
+			enable="$2 $enable"
+			if [ "$2" = "" ]; then
 				echo "Invalid use of --enable"
-				break;
+				exit 1
 			fi
 			shift 2
 			;;
 		--enable=* | --with=*)
-			enable=${1#*=}
+			enable="${1#*=} $enable"
 			shift
 			;;
 		-d | --disable | --without)
-			disable=$2
-			if [ "$disable" = "" ]; then
+			disable="$2 $disable"
+			if [ "$2" = "" ]; then
 				echo "Invalid use of --disable"
-				break;
+				exit 1
 			fi
 			shift 2
 			;;
 		--disable=* | --without=*)
-			disable=${1#*=}
+			disable="${1#*=} $disable"
 			shift
 			;;
 		--target-device | -t)
@@ -441,12 +452,41 @@ do
 			break
 			;;
 	esac
-	
-	set_feature "$enable" 1
-	enable=
-	set_feature "$disable" 0
-	disable=
-	TARGET=$target_device
+done
+
+# Flags (possible values: 0=disabled, 1=enabled, -2=autodetect)
+# Set most flags to -2 (autodetect)
+gmu_core=1
+tool_gmuc=${auto_detect}
+dec_opus=${auto_detect}
+dec_mpg123=${auto_detect}
+dec_gme=${auto_detect}
+dec_vorbis=${auto_detect}
+dec_musepack=${auto_detect}
+dec_flac=${auto_detect}
+dec_speex=${auto_detect}
+dec_modplug=${auto_detect}
+dec_openmpt=${auto_detect}
+dec_wavpack=${auto_detect}
+fe_sdl=${auto_detect}
+fe_web=${auto_detect}
+fe_lirc=${auto_detect}
+fe_log=${auto_detect}
+fe_notify=${auto_detect}
+feature_medialib=0
+feature_sdl_gfx=${auto_detect}
+feature_sdl_ttf=${auto_detect}
+feature_debug=0
+feature_oss_mixer=1
+
+TARGET=$target_device
+
+for i in ${enable}; do
+    set_feature "$i" 1
+done
+
+for i in ${disable}; do
+    set_feature "$i" 0
 done
 
 INCLUDE_PATHS="$INCLUDE_PATHS $includes"
@@ -497,15 +537,17 @@ if test_lib "SDL_gfx"; then
 	feature_sdl_gfx=0
 fi
 
-includes_test="#ifndef _XOPEN_SOURCE_EXTENDED
-#define _XOPEN_SOURCE_EXTENDED
-#endif
-#include <curses.h>"
-includes_test_flags="-I$BASE_INCLUDE_PATH/ncursesw"
-libs_test="-lncursesw"
-code_test="int testvar = WACS_VLINE;"
-test_lib "ncursesw"
-tool_gmuc=$?
+if [ "$tool_gmuc" != 0 ]; then
+	includes_test="#ifndef _XOPEN_SOURCE_EXTENDED
+	#define _XOPEN_SOURCE_EXTENDED
+	#endif
+	#include <curses.h>"
+	includes_test_flags="-I$BASE_INCLUDE_PATH/ncursesw"
+	libs_test="-lncursesw"
+	code_test="int testvar = WACS_VLINE;"
+	test_lib "ncursesw"
+	tool_gmuc=$?
+fi
 
 if [ "$dec_opus" != 0 ]; then
 	includes_test="#include <opus/opus.h>
